const MIN_NUMBER_ITEMS_IN_CART = 0;
const MIN_NUMBER_SELECTED_ITEMS = 0;
const BUTTON_TITLE_ORDER = 'Перейти к заказу';
const BUTTON_TITLE_PAYMENT = 'Оформить заказ';
const BUTTON_TITLE_CHANGE_ADRESS = 'Изменить адрес';

export {
  BUTTON_TITLE_ORDER,
  BUTTON_TITLE_PAYMENT,
  MIN_NUMBER_ITEMS_IN_CART,
  MIN_NUMBER_SELECTED_ITEMS,
  BUTTON_TITLE_CHANGE_ADRESS,
};
