image: creatiwww/docker-compose:latest

services:
  - docker:dind

variables:
  STAGE_IMAGE_FRONTEND_TAG: registry.gitlab.com/g4687/gute.tech-frontend/frontend:stage
  STAGE_API_URL: https://api-stage.gute.tech/api
  PROD_IMAGE_FRONTEND_TAG: registry.gitlab.com/g4687/gute.tech-frontend/frontend:prod
  PROD_API_URL: https://api.gute.tech/api

stages:
  - build
  - deploy

build-for-stage:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
    - echo "IMAGE_FRONTEND_TAG=$STAGE_IMAGE_FRONTEND_TAG" >> .env
    - echo "NEXT_PUBLIC_API_URL=$STAGE_API_URL" >> .env
    - docker-compose -f docker-compose.build.yml -p frontend-stage build
    - docker-compose -f docker-compose.build.yml -p frontend-stage push
  only:
    - stage

build-for-prod:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
    - echo "IMAGE_FRONTEND_TAG=$PROD_IMAGE_FRONTEND_TAG" >> .env
    - echo "NEXT_PUBLIC_API_URL=$PROD_API_URL" >> .env
    - docker-compose -f docker-compose.prod.yml -p frontend-prod build
    - docker-compose -f docker-compose.prod.yml -p frontend-prod push
  only:
    - main

deploy-to-stage:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
    - echo "IMAGE_FRONTEND_TAG=$STAGE_IMAGE_FRONTEND_TAG" >> .env
    - echo "NEXT_PUBLIC_API_URL=$STAGE_API_URL" >> .env
    - docker-compose -f docker-compose.stage.yml -p frontend-stage down
    - docker-compose -f docker-compose.stage.yml -p frontend-stage pull
    - docker-compose -f docker-compose.stage.yml -p frontend-stage up -d
  only:
    - stage
  when: manual

deploy-to-prod:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
    - echo "IMAGE_FRONTEND_TAG=$PROD_IMAGE_FRONTEND_TAG" >> .env
    - echo "NEXT_PUBLIC_API_URL=$PROD_API_URL" >> .env
    - docker-compose -f docker-compose.prod.yml -p frontend-prod down
    - docker-compose -f docker-compose.prod.yml -p frontend-prod pull
    - docker-compose -f docker-compose.prod.yml -p frontend-prod up -d
  only:
    - main
  when: manual
