version: '3.8'

services:
  gutetech-front:
    container_name: gutetech-front
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    volumes:
      - .:/app
      - ./app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
