version: '3.3'

services:
  frontend:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
