version: '3.3'

services:
  frontend:
    image: ${IMAGE_FRONTEND_TAG}
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
