export enum InputIds {
  HEADER_CAR_SELECTION = 'HEADER_CAR_SELECTION',
  HEADER_MODEL_SELECTION = 'HEADER_MODEL_SELECTION',
  HEADER_YEAR_SELECTION = 'HEADER_YEAR_SELECTION',
  HEADER_ENGINE_SELECTION = 'HEADER_ENGINE_SELECTION',
}

export type InputId = keyof typeof InputIds;
